version: '3.8'
services:
    npm:
        build: ./backend
        volumes:
            - ./backend:/app
        entrypoint: ['npm']
        env_file:
            - ./envs/backend.dev.env

    f-npm:
        build: ./frontend
        volumes:
            - ./frontend:/app
        entrypoint: ['npm']

    # imp
    f-build:
        build: ./frontend
        volumes:
            - ./frontend/src:/app/src
            - f_modules:/app/node_modules
            - f-build-data:/app/build

    api:
        build: ./backend
        volumes:
            - ./backend/src:/app/src
            - api_modules:/app/node_modules
        env_file:
            - ./envs/backend.dev.env
        entrypoint: ['npm', 'run', 'dev']
        ports:
            - 8000:8000

    nginx:
        build: ./nginx
        volumes:
            - f-build-data:/usr/share/nginx/html
        ports:
            - 80:80
        depends_on:
            - api
            - f-build

volumes:
    f-build-data:
    f_modules:
    api_modules:
